### PR TITLE
fixed css

### PR DESCRIPTION
**Pull request by ujen5173**

### CODE REVIEW

**Review by shankarlohar — CHANGES_REQUESTED** [review]
Hey, fix the merge Conflicts and show me what you changed. 😊 Let me know if you need any help

**Review by shankarlohar — APPROVED** [review]

**Comment by shankarlohar** [comment]
Redo it whatever you did broke the page. Sorry. And give me conflict free code. and don't change 2000-3000 lines at once its hard to monitor.
Please give me screenshots of before and after your patch.

**Comment by ujen5173** [comment]
@shankarlohar, Ohh Sorry for the conflict. This was my first pull request so I was confused about what to do. That change was because of a prettier extension. The code was not formatted and there were many HTML tag errors. I have fixed the HTML tag errors.  Can you guide me on what to do now?

These are the changes I made:
```
/* Scroll-bar Customization */
body::-webkit-scrollbar {
  width: 17px;
}
body::-webkit-scrollbar-thumb {
  background: rgba(0, 0, 0, 0.6);
  border: 4px solid white;
  border-radius: 10px;
}
body::-webkit-scrollbar-thumb:hover {
  background: rgba(0, 0, 0, 0.4);
}
```
```
.sidebar::-webkit-scrollbar {
  width: 10px;
  background-color: transparent;
}

.sidebar::-webkit-scrollbar-thumb {
  border-radius: 15px;
}

.sidebar:hover::-webkit-scrollbar-thumb {
  /* width: 5px; */
  background-color: rgba(0, 0, 0, 0.2);
}

```

**Comment by shankarlohar** [comment]
> @shankarlohar, Ohh Sorry for the conflict. This was my first pull request so I was confused about what to do. That change was because of a prettier extension. The code was not formatted and there were many HTML tag errors. I have fixed the HTML tag errors. Can you guide me on what to do now?
> 
> These are the changes I made:
> 
> ```
> /* Scroll-bar Customization */
> body::-webkit-scrollbar {
>   width: 17px;
> }
> body::-webkit-scrollbar-thumb {
>   background: rgba(0, 0, 0, 0.6);
>   border: 4px solid white;
>   border-radius: 10px;
> }
> body::-webkit-scrollbar-thumb:hover {
>   background: rgba(0, 0, 0, 0.4);
> }
> ```
> 
> ```
> .sidebar::-webkit-scrollbar {
>   width: 10px;
>   background-color: transparent;
> }
> 
> .sidebar::-webkit-scrollbar-thumb {
>   border-radius: 15px;
> }
> 
> .sidebar:hover::-webkit-scrollbar-thumb {
>   /* width: 5px; */
>   background-color: rgba(0, 0, 0, 0.2);
> }
> ```

#### You can ask as many question you want let do it this way first.

Try adding your code with these steps:
- First of all pull the recent changes from the repository as there are people giving pull requests every 10 min.
- Now only add/change the line of code you want to in the css file.
- Run the change on your local server (if using vscode then use liveserver extension ) now if you see the changes you made is working fine on the website. then
- run a pull command again to see if there are changes again.
If there are no changes push the code and give me a pull request. If there are changes then pull them and resolve the conflicts (these are just your code overlapping with someone else) wherever needed. and then commit - push and send pull request to me.

> PS: Take Screenshots from your liveserver of the change and add it to the pull request to show me what you changed visually so that I get a little help while reading your changes.

**Pull request merged**
