### PR TITLE
Added my card

### PR DESCRIPTION
**Pull request by ananyaa07**
Please accept this pull request @shankarlohar

### CODE REVIEW

**Comment by ananyaa07** [comment]
@shankarlohar I had three pr merged from your side for the hactober fest, but now it is showing that your repo has been excluded, why is it so?

**Comment by shankarlohar** [comment]
> @shankarlohar I had three pr merged from your side for the hactober fest, but now it is showing that your repo has been excluded, why is it so?

Show me the screenshots. 
I have already completed my fest with this repository only and no one complained yet.

**Comment by shankarlohar** [comment]
> @shankarlohar I had three pr merged from your side for the hactober fest, but now it is showing that your repo has been excluded, why is it so?

@ananyaa07 and please see... Hacktober fest accepted 4+3 merged pull request at most and rest will be exclude.

See below for my accepted requests

**Comment by ananyaa07** [comment]
@shankarlohar 
image

**Comment by shankarlohar** [comment]
> @shankarlohar 
> image
> 

How many got accepted yet?

**Comment by ananyaa07** [comment]
3 are accepted currently, and most of the pr which i made was with the help of you repo( which I made 7 days before)

**Comment by ananyaa07** [comment]
I dont know why they got excluded

**Comment by ananyaa07** [comment]
If possible, please look into this matter and talk to authorities as my 1 pull request still remains @shankarlohar 
Thanking Your Anticipation

**Comment by shankarlohar** [comment]
> If possible, please look into this matter and talk to authorities as my 1 pull request still remains @shankarlohar 
> Thanking Your Anticipation

Text me on Instagram I need to know something. @shankarloharig

**Pull request merged**
